### ISSUE TITLE
deleting session

### ISSUE THREAD

**Issue by Theolodewijk** [zpweber/MySQLSessionHandler#1]
How to delete session?

require('MySQLSessionHandler.php');
$sesHandler = new MySQLSessionHandler(new mysqli($sql_host, $sql_user, $sql_pass, $sql_dbname));
$sesHandler->destroy(session_id()); ??

**Comment by zpweber** [comment]
MySQLSessionHandler::destroy() is not meant to be called directly, instead use the builtin global function session_destroy()   (no need to include sid as this function closes the session that is currently started).

[http://php.net/manual/en/function.session-destroy.php](http://php.net/manual/en/function.session-destroy.php)

**Comment by Theolodewijk** [comment]
I have tried session_destroy(); but it doesn't delete the session in the database.

I don't think this is the right way but when I use this the session will delete, cookie will delete and also delete the session from the database.

require('MySQLSessionHandler.php');
$sesHandler = new MySQLSessionHandler(new mysqli($sql_host, $sql_user, $sql_pass, $sql_dbname));
$sesHandler->start();

session_write_close();

$sesHandler->destroy(session_id());
$sesHandler->close();

setcookie($session_name, null, -1, '/');

**Comment by Theolodewijk** [comment]
sorry spending your time, I have fix it so as you told.

Thanks
